### ISSUE TITLE
Incorrect handling of UTF8 messages

### ISSUE THREAD

**Issue by blelump** [nats-io/ruby-nats-streaming#12]
Hi,

#### the problem:
when you try to send a message with any UTF8 character, it fails

#### actual result:
it raises with:
```
/bundle_cache/gems/nats-streaming-0.2.2/lib/stan/client.rb:193:in `initialize': U+0100 from UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)                            
        from /bundle_cache/gems/nats-streaming-0.2.2/lib/stan/client.rb:193:in `new'                                                                                            
        from /bundle_cache/gems/nats-streaming-0.2.2/lib/stan/client.rb:193:in `publish'
```

As stated [here](https://github.com/protocolbuffers/protobuf/issues/4228), using `#b` on message string resolves the problem.

**Comment by blelump** [comment]
Thanks @wallyqs . Wouldn't it be safer to always use `#b` on any sending message? I know this is extra effort to encode to `ASCII-8BIT`, but on the other hand any UTF8 character may crash sending the whole message, which sounds like a much worse scenario. I'd vote for support UTF8 by default.

**Comment by wallyqs** [comment]
@blelump I think you're right, it would be both more convenient and handling as bytes using `#b` throughout would be closer to treating the payload opaquely which is one of the things that we try to do in the clients. Thanks for the feedback!

**Comment by acro5piano** [comment]
Just a note, I'm writing payload in JSON format. In this case, `ascii_only: true` is handy option.

```rb
decoded_payload = JSON.generate({ hello: 'こんにちは！' }, ascii_only: true)

sc.publish(subject, decoded_payload) do |guid, error|
end
```
